#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 006 - Comprehensive Testing Infrastructure

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Czech MedAI - Testing Infrastructure"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${YELLOW}Project root: $PROJECT_ROOT${NC}"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

echo ""
echo "========================================"
echo "Checking Dependencies"
echo "========================================"

# Check if frontend test dependencies are installed
if ! grep -q "vitest" package.json 2>/dev/null; then
    echo -e "${YELLOW}Installing frontend test dependencies...${NC}"
    pnpm add -D vitest @vitest/coverage-v8 @vitejs/plugin-react @testing-library/react @testing-library/jest-dom @testing-library/user-event jsdom
fi

# Check if backend test dependencies are installed
if ! pip show pytest-cov >/dev/null 2>&1; then
    echo -e "${YELLOW}Installing backend test dependencies...${NC}"
    pip install pytest-cov
fi

echo -e "${GREEN}Dependencies ready${NC}"

# ============================================
# START SERVICES (Optional - for integration testing)
# ============================================

echo ""
echo "========================================"
echo "Starting Services (Optional)"
echo "========================================"

# Ask user if they want to start services
read -p "Start development servers for integration testing? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Backend
    echo "Starting Backend..."
    cd "$PROJECT_ROOT/backend"
    uvicorn app.main:app --reload --port 8000 &
    BACKEND_PID=$!
    cd "$PROJECT_ROOT"
    wait_for_service 8000 "Backend"

    # Frontend
    echo "Starting Frontend..."
    pnpm dev &
    FRONTEND_PID=$!
    wait_for_service 3000 "Frontend"

    echo ""
    echo -e "${GREEN}Services running:${NC}"
    echo "  Backend PID: $BACKEND_PID"
    echo "  Frontend PID: $FRONTEND_PID"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Testing!"
echo "========================================"
echo ""
echo "Test Commands:"
echo "  Frontend:  pnpm test"
echo "  Frontend:  pnpm test:coverage"
echo "  Backend:   cd backend && python -m pytest tests/ -v"
echo "  Backend:   cd backend && python -m pytest --cov=. tests/"
echo ""
echo "Services (if started):"
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:8000"
echo ""
echo "To stop services: kill \$BACKEND_PID \$FRONTEND_PID"
echo ""
