#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for LangChain Dependency Upgrade

set -e

echo "========================================"
echo "Starting Development Environment"
echo "LangChain 0.3.x Upgrade Task"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking environment variables..."

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${YELLOW}WARNING: ANTHROPIC_API_KEY not set${NC}"
    echo "  LangChain-Anthropic requires this for Claude model integration"
fi

if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${YELLOW}WARNING: OPENAI_API_KEY not set${NC}"
    echo "  LangChain-OpenAI requires this for embeddings in RAG pipeline"
fi

# ============================================
# BACKEND SERVICE (Python/FastAPI)
# ============================================

echo ""
echo "Starting Backend Service..."
cd backend

# Activate virtual environment if it exists
if [ -d "venv" ]; then
    echo "Activating Python virtual environment..."
    source venv/bin/activate
else
    echo -e "${YELLOW}WARNING: No virtual environment found in backend/venv${NC}"
fi

# Check if dependencies are installed
echo "Verifying LangChain packages..."
if ! pip list | grep -q "langchain"; then
    echo -e "${RED}ERROR: LangChain not installed. Run: pip install -r requirements.txt${NC}"
    exit 1
fi

# Display current LangChain versions
echo ""
echo "Current LangChain package versions:"
pip list | grep -E 'langchain|langgraph'
echo ""

# Start backend server
echo "Starting FastAPI backend on port 8000..."
uvicorn main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

wait_for_service 8000 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  Health:   http://localhost:8000/health"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "Environment Variables:"
echo "  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:+SET}"
echo "  OPENAI_API_KEY:    ${OPENAI_API_KEY:+SET}"
echo ""
echo "Processes:"
echo "  Backend PID: $BACKEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
echo "========================================"
echo "Ready for LangChain 0.3.x Upgrade Task"
echo "========================================"
