#!/bin/bash

# Auto-Build Environment Setup for E2E Testing Suite
# Generated by Planner Agent - Session 1
# Spec: 004-end-to-end-testing-suite

set -e

echo "========================================"
echo "E2E Testing Suite - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Install npm packages (including Playwright when added to package.json)
npm install

# Check if Playwright is in package.json
if grep -q "@playwright/test" package.json; then
    echo -e "${GREEN}@playwright/test found in package.json${NC}"

    # Install Playwright browsers
    echo "Installing Playwright browsers..."
    npx playwright install --with-deps
else
    echo -e "${YELLOW}@playwright/test not yet in package.json - will be added in Phase 1${NC}"
fi

# ============================================
# ENVIRONMENT VARIABLES CHECK
# ============================================

echo ""
echo "Checking environment variables..."

# Required for frontend
required_vars=(
    "NEXT_PUBLIC_SUPABASE_URL"
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
    "NEXT_PUBLIC_API_URL"
)

# Optional for E2E tests (needed in CI)
optional_vars=(
    "TEST_USER_EMAIL"
    "TEST_USER_PASSWORD"
)

for var in "${required_vars[@]}"; do
    if [ -z "${!var}" ]; then
        # Check .env and .env.local files
        if grep -q "^${var}=" .env 2>/dev/null || grep -q "^${var}=" .env.local 2>/dev/null; then
            echo -e "${GREEN}$var: Found in .env file${NC}"
        else
            echo -e "${YELLOW}$var: Not set (check .env or .env.local)${NC}"
        fi
    else
        echo -e "${GREEN}$var: Set${NC}"
    fi
done

for var in "${optional_vars[@]}"; do
    if [ -z "${!var}" ]; then
        echo -e "${YELLOW}$var: Not set (needed for E2E test runs)${NC}"
    else
        echo -e "${GREEN}$var: Set${NC}"
    fi
done

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Development Servers"
echo "========================================"

# Start Next.js development server
echo "Starting Next.js frontend..."
npm run dev &
FRONTEND_PID=$!

# Wait for frontend
wait_for_service 3000 "Frontend (Next.js)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Key URLs for E2E Testing:"
echo "  Login:     http://localhost:3000/auth/login"
echo "  Dashboard: http://localhost:3000/dashboard"
echo "  Chat:      http://localhost:3000/dashboard/chat"
echo "  VZP:       http://localhost:3000/dashboard/vzp-navigator"
echo ""
echo "Playwright Commands (after setup):"
echo "  npx playwright test              # Run all tests"
echo "  npx playwright test --ui         # Interactive UI mode"
echo "  npx playwright test --list       # List all tests"
echo "  npx playwright show-report       # View HTML report"
echo ""
echo -e "${YELLOW}Note: Backend (port 8000) must be started separately for full E2E tests${NC}"
echo ""
echo "Press Ctrl+C to stop all services"

# Wait for user interrupt
wait $FRONTEND_PID
