#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for E2E Test Suite
# Spec: 007-testy

set -e

echo "========================================"
echo "Starting Development Environment"
echo "E2E Test Suite for MedAI"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment..."

# Check Node.js
if command -v node &> /dev/null; then
    echo -e "${GREEN}✓ Node.js found: $(node --version)${NC}"
else
    echo -e "${RED}✗ Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

# Check pnpm/npm
if command -v pnpm &> /dev/null; then
    PKG_MANAGER="pnpm"
    echo -e "${GREEN}✓ pnpm found${NC}"
elif command -v npm &> /dev/null; then
    PKG_MANAGER="npm"
    echo -e "${YELLOW}! Using npm (pnpm preferred)${NC}"
else
    echo -e "${RED}✗ No package manager found${NC}"
    exit 1
fi

# Check Python for backend
if command -v python3 &> /dev/null; then
    echo -e "${GREEN}✓ Python found: $(python3 --version)${NC}"
else
    echo -e "${YELLOW}! Python not found - backend tests may not work${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Install frontend dependencies
$PKG_MANAGER install

# Install Playwright browsers (if Playwright is installed)
if [ -f "node_modules/@playwright/test/package.json" ]; then
    echo "Installing Playwright browsers..."
    npx playwright install chromium
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Start Next.js frontend (background)
echo "Starting Next.js frontend on port 3000..."
npm run dev &
FRONTEND_PID=$!

# Wait for frontend
wait_for_service 3000 "Frontend"

# Optionally start backend
if [ -d "backend" ]; then
    echo "Starting Python backend on port 8000..."
    cd backend
    if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt -q 2>/dev/null || true
    fi
    uvicorn app.main:app --reload --port 8000 &
    BACKEND_PID=$!
    cd ..
    wait_for_service 8000 "Backend"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:8000"
echo ""
echo "Key URLs:"
echo "  Login:     http://localhost:3000/auth/login"
echo "  Dashboard: http://localhost:3000/dashboard"
echo "  Chat:      http://localhost:3000/dashboard/chat"
echo "  VZP:       http://localhost:3000/dashboard/vzp-navigator"
echo ""
echo "E2E Test Commands:"
echo "  Run all tests:    npx playwright test"
echo "  Run with UI:      npx playwright test --ui"
echo "  Run headed:       npx playwright test --headed"
echo "  Show report:      npx playwright show-report"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
